services:
  postgres:
    image: postgres:15
    container_name: purplemerit-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: purplemerit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: purplemerit-redis

  backend:
    build: ./backend
    container_name: purplemerit-backend
    command: npm run start:dev
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
